sonar.organization=levongabrielyan04
sonar.projectKey=LevonGabrielyan04_dropkey

sonar.sources=app,resources/js
sonar.tests=tests

sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/public/**,**/bootstrap/**,**/database/**,**/routes/**,**/config/**,**/resources/views/**,**/*.blade.php
sonar.test.inclusions=tests/**,resources/js/**/*.test.js

sonar.php.coverage.reportPaths=build/php-coverage.xml
sonar.javascript.lcov.reportPaths=build/js-coverage/lcov.info

sonar.coverage.exclusions=**/tests/**,**/*.test.js,**/database/**,**/routes/**,**/config/**,**/resources/views/**
